### ISSUE TITLE
Featured profile function

### ISSUE THREAD

**Issue by JeremyRubin** [dennisreimann/bitcoin-donations#24]
If passed an arg on the URL e.g., ?dev=JeremyRubin, the page should display that dev on top taking up a whole row and the other devs below (or something similar).

This would make it easier to share links to specific devs while also keeping traffic on bitcoindevlist.com to see other devs who might be good to fund.

**Comment by dennisreimann** [comment]
Good idea, will add this next week :)

**Comment by dennisreimann** [comment]
Added [featured profiles](https://bitcoindevlist.com/jeremy-rubin/) as well as tags:

* [Bitcoin Core](https://bitcoindevlist.com/tag/bitcoin-core/)
* [BTCPay Server](https://bitcoindevlist.com/tag/btcpay-server/)

🚀
