### ISSUE TITLE
Feature Request: Add multiple donation links

### ISSUE THREAD

**Issue by Zaxounette** [dennisreimann/bitcoin-donations#3]
This issue requests to add multiple donation fields/link to each submission. Some people have for example a github sponsor page AND a bitcoin donation page.
Both could be visible at the same time to provide more options. Options is good :) 

UX example:
![Screenshot_76](https://user-images.githubusercontent.com/51208677/88841879-dda8e600-d1de-11ea-82ab-3d8f2bc51f06.png)

**Ideally**, additional donation links & fields are invisible/inactive until proper field in data.js is populated.

**Comment by dennisreimann** [comment]
IMHO it complicated things and I see this is an edge case: Most people have a prefered way of accepting donations – if there are multiple one could set up a landing page and link to that.

I'll leave this open for discussion 😀

**Comment by PatrickLemke** [comment]
I agree with Dennis. Having your own landing page is better because you can put additional infos there. The UI should stay nice and clean and one developer should not have more space than another.

**Comment by dennisreimann** [comment]
Also added the option to add links via Markdown in the `description` field, so I think this is obsolete :)

**Comment by Zaxounette** [comment]
> one developer should not have more space than another.

I like that point of view and support that argument.

> Also added the option to add links via Markdown in the `description` field, so I think this is obsolete :)

That's good to know ! 

This Issue then might be indeed obsolete.
Will leave initiative to close issue to maintainers if chosen so.
